micronaut:
    application:
        name: compensator-api
    router:
        static-resources:
            swagger:
                paths: classpath:META-INF/swagger
                mapping: /swagger/**

# Health check
endpoints:
  health:
    enabled: true
    details-visible: ANONYMOUS
        
refresh:
    updateTimeFormat: yyyy-MM-dd HH:mm:ss

# TMS APIs
tms:
    api-url: https://api.qvantel.com/masmovil
    version: V3
    entity: revenue
    endpoint-creditnote: subscriptions-apply-credit-note
    endpoint-fat: subscriptions-apply-fat    

# Masmovil Configuration
masmovil:
    header:
        xCorrelationId: X-Correlation-ID
        xRequestId: X-Request-ID
    log:
        data: data
        path: path
        methodName: methodName
